import { motion } from 'framer-motion';
import { Download, Share2, CheckCircle2, ChevronRight, Loader2 } from 'lucide-react';
import { useState } from 'react';
// @ts-ignore
import html2pdf from 'html2pdf.js';

export default function Report() {
    const [isExporting, setIsExporting] = useState(false);

    const handleExport = () => {
        setIsExporting(true);
        const element = document.getElementById('report-content');

        // We add a slight delay to allow the exporting state to render
        setTimeout(() => {
            const opt: any = {
                margin: 0.5,
                filename: 'TrueNorth_AIFE_Report.pdf',
                image: { type: 'jpeg' as const, quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
            };

            if (element) {
                html2pdf().from(element as HTMLElement).set(opt).save().then(() => {
                    setIsExporting(false);
                });
            } else {
                setIsExporting(false);
            }
        }, 100);
    };

    return (
        <div className="max-w-4xl mx-auto w-full pb-12">

            {/* Action Bar */}
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 mb-8 bg-white/80 p-4 rounded-xl border border-slate-200 shadow-sm">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900">Your Personal Action Report</h1>
                    <p className="text-slate-500 text-sm">Generated by Glowie based on your session</p>
                </div>
                <div className="flex gap-3">
                    <button
                        onClick={handleExport}
                        disabled={isExporting}
                        className="flex items-center gap-2 px-4 py-2 bg-white hover:bg-slate-50 text-slate-700 rounded-lg transition-colors border border-slate-200 shadow-sm disabled:opacity-50 font-medium"
                    >
                        {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                        <span className="hidden sm:inline">{isExporting ? 'Exporting...' : 'Export PDF'}</span>
                    </button>
                    <button className="flex items-center gap-2 px-4 py-2 bg-tn-primary hover:bg-tn-primary/80 text-white rounded-lg transition-colors">
                        <Share2 className="w-4 h-4" />
                        <span className="hidden sm:inline">Share</span>
                    </button>
                </div>
            </div>

            {/* Report Content - This would be the target for html2pdf */}
            <motion.div
                id="report-content"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-white text-slate-900 rounded-2xl p-8 md:p-12 shadow-xl border border-slate-200 relative overflow-hidden"
            >
                {/* Decorative Header */}
                <div className="absolute top-0 left-0 w-full h-3 bg-gradient-to-r from-tn-primary via-tn-secondary to-tn-accent" />

                <header className="flex justify-between items-end border-b border-slate-200 pb-8 mb-8">
                    <div>
                        <h2 className="text-3xl font-serif font-bold text-slate-900 mb-2">AIFE Session Insights</h2>
                        <p className="text-slate-500 font-medium">True North • Designing for AGENCY</p>
                    </div>
                    <div className="text-right">
                        <p className="text-slate-400 text-sm uppercase tracking-wider font-semibold">Date</p>
                        <p className="text-slate-700 font-medium">{new Date().toLocaleDateString()}</p>
                    </div>
                </header>

                <section className="mb-12">
                    <h3 className="text-xl font-bold text-tn-primary mb-4 flex items-center gap-2">
                        <CheckCircle2 className="w-6 h-6" />
                        Current State Assessment
                    </h3>
                    <p className="text-slate-700 text-lg leading-relaxed mb-6">
                        Based on our conversation, as a Tech Director, you are well-positioned to drive systemic change. Your primary focus currently aligns with the <strong>Institutional (RISE)</strong> pathway, grappling with the tension between the Path of Control and the Path of Agency.
                    </p>

                    <div className="bg-slate-50 rounded-xl p-6 border border-slate-100">
                        <h4 className="font-semibold text-slate-900 mb-3">Key Strengths Identified:</h4>
                        <ul className="space-y-2">
                            <li className="flex items-start gap-2 text-slate-700">
                                <ChevronRight className="w-5 h-5 text-tn-primary shrink-0 mt-0.5" />
                                <span>Strong desire to move away from purely reactive, fear-based AI policies.</span>
                            </li>
                            <li className="flex items-start gap-2 text-slate-700">
                                <ChevronRight className="w-5 h-5 text-tn-primary shrink-0 mt-0.5" />
                                <span>Commitment to human-centered design and keeping "humans in the loop."</span>
                            </li>
                        </ul>
                    </div>
                </section>

                <section className="mb-12">
                    <h3 className="text-xl font-bold text-tn-secondary mb-4 flex items-center gap-2">
                        <CheckCircle2 className="w-6 h-6" />
                        Your RISE Action Plan
                    </h3>
                    <div className="grid sm:grid-cols-2 gap-6">
                        <div className="bg-white border rounded-xl p-5 shadow-sm">
                            <div className="w-8 h-8 rounded-full bg-tn-secondary/10 text-tn-secondary flex items-center justify-center font-bold mb-4">1</div>
                            <h4 className="font-bold text-slate-900 mb-2">Reframe the Policy</h4>
                            <p className="text-slate-600 text-sm">Shift your school's AI guidelines from a "Red Flag Act" (restricting usage) to a framework that promotes "Pioneer Mindset" exploration safely.</p>
                        </div>
                        <div className="bg-white border rounded-xl p-5 shadow-sm">
                            <div className="w-8 h-8 rounded-full bg-tn-secondary/10 text-tn-secondary flex items-center justify-center font-bold mb-4">2</div>
                            <h4 className="font-bold text-slate-900 mb-2">Establish True North</h4>
                            <p className="text-slate-600 text-sm">Gather leadership to define your institution's non-negotiable core values regarding technology and human agency.</p>
                        </div>
                        <div className="bg-white border rounded-xl p-5 shadow-sm">
                            <div className="w-8 h-8 rounded-full bg-tn-secondary/10 text-tn-secondary flex items-center justify-center font-bold mb-4">3</div>
                            <h4 className="font-bold text-slate-900 mb-2">Structure the Shift</h4>
                            <p className="text-slate-600 text-sm">Audit existing workflows. Where can AI save time, and explicitly, where will that saved time be reinvested into human connections?</p>
                        </div>
                        <div className="bg-white border rounded-xl p-5 shadow-sm border-tn-secondary/30 ring-1 ring-tn-secondary/10">
                            <div className="w-8 h-8 rounded-full bg-tn-secondary flex items-center justify-center text-white font-bold mb-4">4</div>
                            <h4 className="font-bold text-slate-900 mb-2">Evaluate Impact</h4>
                            <p className="text-slate-600 text-sm">Implement ongoing feedback loops with students and teachers. Ensure the agency model is actually empowering learners, not just automating tasks.</p>
                        </div>
                    </div>
                </section>

                <footer className="mt-16 pt-8 border-t border-slate-200 text-center">
                    <p className="text-slate-500 font-medium mb-2">Ready for the next step?</p>
                    <p className="text-slate-600 text-sm">
                        Join the waitlist for TrueNorthEd.tech to track these goals and transform your school's culture.
                    </p>
                </footer>

            </motion.div>
        </div>
    );
}
